import * as fs from "fs";
const gadify_mockdata = {
  id: 1,
  submissionId: 1,
  evaluatorId: 1,
  createdAt: "2025-03-12T21:43:49.000Z",
  updatedAt: "2025-03-12T21:43:49.000Z",
  submission: {
    id: 1,
    submissionId: "SUB-0001",
    proponentId: 2,
    fileType: "File",
    proposalTitle:
      "An Investigation of Mechanical Vibrations in High-Speed Rotors",
    proposalDescription: "This is the description of proposal 1.",
    submissionStatus: "OnHold",
  },
  evaluator: {
    id: 1,
    officeId: 2,
    fullName: "Test",
    email: "Test@gmail.com",
  },
  assessments: [
    {
      id: 1,
      sectionId: 1,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "0.5",
      comments: "Partial participation observed in stakeholder meetings.",
      section: {
        id: 1,
        element:
          "1.0 Involvement of women and men (max score: 2; 1 for each item)",
        isMainSection: true,
      },
    },
    {
      id: 2,
      sectionId: 2,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: true,
      doneYes: false,
      score: "0.5",
      comments: "Partial participation observed in stakeholder meetings.",
      section: {
        id: 2,
        element:
          "1.1 Participation of women and men in beneficiary groups in problem identification (possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 3,
      sectionId: 3,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "All necessary gender-based data collected.",
      section: {
        id: 3,
        element:
          "1.2 Participation of women and men in beneficiary groups in project design (possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 4,
      sectionId: 4,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: true,
      doneYes: false,
      score: "0.0",
      comments: "No gender analysis conducted.",
      section: {
        id: 4,
        element:
          "2.0 Collection of sex-disaggregated data and gender-related information (possible scores: 0, 1.0, 2.0)",
        isMainSection: true,
      },
    },
    {
      id: 5,
      sectionId: 5,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "1.0",
      comments:
        "Some gender equality goals identified, but not fully developed.",
      section: {
        id: 5,
        element:
          "3.0 Conduct of gender analysis and identification of gender issues (max score: 2; 1 for each item)",
        isMainSection: true,
      },
    },
    {
      id: 6,
      sectionId: 6,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strategies fully aligned with identified gender issues.",
      section: {
        id: 6,
        element:
          "3.1 Analysis of gender gaps and inequalities related to gender roles, perspectives and needs, or access to and control of resources (possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 7,
      sectionId: 7,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: true,
      doneYes: false,
      score: "1.0",
      comments: "Potential impacts identified but require further study.",
      section: {
        id: 7,
        element:
          "3.2 Analysis of constraints and opportunities related to women and men’s participation in the project (possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 8,
      sectionId: 8,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: true,
      doneYes: false,
      score: "2.0",
      comments: "Clear gender-focused targets included in the M&E framework.",
      section: {
        id: 8,
        element:
          "4.0 Gender equality goals, outcomes, and outputs (possible scores: 0, 1.0, 2.0)",
        isMainSection: true,
      },
    },
    {
      id: 9,
      sectionId: 9,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "0.0",
      comments: "No explicit requirement for sex-disaggregated data in M&E.",
      section: {
        id: 9,
        element:
          "5.0 Matching of strategies with gender issues (possible scores: 0, 1.0, 2.0)",
        isMainSection: true,
      },
    },
    {
      id: 10,
      sectionId: 10,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "1.0",
      comments: "Limited budget allocated for gender-related efforts.",
      section: {
        id: 10,
        element:
          "6.0 Gender analysis of likely impacts of the project (max score: 2; for each item or question, 0.67)",
        isMainSection: true,
      },
    },
    {
      id: 11,
      sectionId: 11,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 11,
        element:
          "6.1 Are women and girl children among the direct or indirect beneficiaries? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
    {
      id: 12,
      sectionId: 12,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 12,
        element:
          "6.2 Has the project considered its long-term impact on women’s socioeconomic status and empowerment? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
    {
      id: 13,
      sectionId: 13,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 13,
        element:
          "6.3 Has the project included strategies for avoiding or minimizing negative impact on women’s status and welfare? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
    {
      id: 14,
      sectionId: 14,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 14,
        element:
          "7.0 Monitoring targets and indicators (possible scores: 0, 1.0, 2.0)",
        isMainSection: true,
      },
    },
    {
      id: 15,
      sectionId: 15,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 15,
        element:
          "8.0 Sex-disaggregated database requirement (possible scores: 0, 1.0, 2.0)",
        isMainSection: true,
      },
    },
    {
      id: 16,
      sectionId: 16,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 16,
        element: "9.0 Resources (max score: 2; for each question, 1)",
        isMainSection: true,
      },
    },
    {
      id: 17,
      sectionId: 17,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 17,
        element:
          "9.1 Is the project’s budget allotment sufficient for gender equality promotion or integration? (Possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 18,
      sectionId: 18,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 18,
        element:
          "9.2 Does the project have the expertise in promoting gender equality and women’s empowerment? (Possible scores: 0, 0.5, 1.0)",
        isMainSection: false,
      },
    },
    {
      id: 19,
      sectionId: 19,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: false,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 19,
        element:
          "10.0 Relationship with the agency’s GAD efforts (max score: 2; for each question or item, 0.67)",
        isMainSection: true,
      },
    },
    {
      id: 20,
      sectionId: 20,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 20,
        element:
          "10.1 Will the project build on or strengthen the agency/ NCRFW/ government’s commitment to the empowerment of women? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
    {
      id: 21,
      sectionId: 21,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 21,
        element:
          "10.2 Will the project build on the initiatives or actions of other organizations in the area? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
    {
      id: 22,
      sectionId: 22,
      submissionEvaluationId: 1,
      doneNo: false,
      donePartly: false,
      doneYes: true,
      score: "2.0",
      comments: "Strong alignment with agency’s gender-related initiatives.",
      section: {
        id: 22,
        element:
          "10.3 Does the project have an exit plan that will ensure the sustainability of GAD efforts and benefits? (Possible scores: 0, 0.33, 0.67)",
        isMainSection: false,
      },
    },
  ],
};

export default gadify_mockdata;
